simpler_grants_vulns:
  outputs:
    default:
      type: duckdb
      threads: 1
      path: target/results.duckdb
      secrets:
      - type: http
        scope: 'https://api.github.com'
        bearer_token: '{{ env_var("DBT_ENV_SECRET_GITHUB_TOKEN", "") }}'
